config firewall vip
    edit "web-vip"
        set extip 10.0.0.1
        set mappedip "192.168.1.2"
        set extintf "port3"
        set portforward enable
        set extport 80
        set mappedport 80
    next
    edit "web-vip-https"
        set extip 10.0.0.1
        set mappedip "192.168.1.2"
        set extintf "port3"
        set portforward enable
        set extport 443
        set mappedport 443
    next
end
