config firewall policy
    edit 1
        set name "vlans-com"
        set srcintf "vlan10" "vlan20"
        set dstintf "vlan20" "vlan10"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
    next
    edit 2
        set name "vpn-net"
        set srcintf "ssl.root"
        set dstintf "port3"
        set action accept
        set srcaddr "SSLVPN_TUNNEL_ADDR1"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 3
        set name "vlans-dmz"
        set srcintf "vlan10" "vlan20"
        set dstintf "port2"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
    next
    edit 4
        set name "dmz-net"
        set srcintf "port2"
        set dstintf "port3"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 5
        set name "vlans-net"
        set srcintf "vlan10" "vlan20"
        set dstintf "port3"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 7
        set name "wan-http"
        set srcintf "port3"
        set dstintf "port2"
        set action accept
        set srcaddr "all"
        set dstaddr "web-vip" "web-vip-https"
        set schedule "always"
        set service "HTTP" "HTTPS"
    next
    edit 8
        set name "vpn-vlan10"
        set srcintf "ssl.root"
        set dstintf "vlan10"
        set action accept
        set srcaddr "SSLVPN_TUNNEL_ADDR1"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
    next
    edit 9
        set name "vpn-vlan20"
        set srcintf "ssl.root"
        set dstintf "vlan20"
        set action accept
        set srcaddr "SSLVPN_TUNNEL_ADDR1"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
    next
    edit 10
        set name "vpn-dmz"
        set srcintf "ssl.root"
        set dstintf "port2"
        set action accept
        set srcaddr "SSLVPN_TUNNEL_ADDR1"
        set dstaddr "server"
        set schedule "always"
        set service "ALL"
    next
end
